"use strict";
const $=id=>document.getElementById(id);
const cfg=window.APP_CONFIG;
let db,user=null,entries=[],section="dashboard";
const sections=[["dashboard","⌂ Dashboard"],["plan","⌁ Future Plans"],["discussion","◌ Discussions"],["game","♟ Couple Games"],["decision","✓ Decisions"],["memory","◇ Memories & Photos"],["bucket","☆ Bucket List"],["date","◷ Important Dates"],["letter","✉ Letters"],["journal","☷ Shared Journal"],["dateidea","♡ Date Ideas"]];
function toast(m){const e=$("toast");if(!e){alert(m);return}e.textContent=m;e.style.display="block";clearTimeout(e.timer);e.timer=setTimeout(()=>e.style.display="none",3500)}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function jsq(v=""){return String(v).replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
function days(a,b){const x=new Date(a),y=new Date(b);return isNaN(x)||isNaN(y)?0:Math.max(0,Math.ceil((y-x)/864e5))}
async function login(){const email=$("email").value.trim(),password=$("password").value,b=$("loginButton");if(!email||!password)return toast("Enter both email and password.");try{b.disabled=true;b.textContent="Opening our universe...";const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;if(!data.session)throw new Error("No session created. Confirm the email account.");await init()}catch(e){console.error(e);toast("Login failed: "+e.message)}finally{b.disabled=false;b.textContent="Enter our universe"}}
async function signup(){const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return toast("Enter both email and password.");try{const {data,error}=await db.auth.signUp({email,password});if(error)throw error;toast(data.session?"Account created.":"Account created. Check the confirmation email.");if(data.session)await init()}catch(e){toast("Signup failed: "+e.message)}}
async function logout(){await db.auth.signOut();location.reload()}
async function init(){const {data,error}=await db.auth.getUser();if(error)throw error;if(!data.user)return;user=data.user;$("auth").hidden=true;$("app").hidden=false;$("nav").innerHTML=sections.map(x=>`<button type="button" data-s="${x[0]}">${esc(x[1])}</button>`).join("");$("nav").querySelectorAll("button").forEach(b=>b.onclick=()=>show(b.dataset.s));$("fType").innerHTML=sections.slice(1).filter(x=>!["discussion","game"].includes(x[0])).map(x=>`<option value="${x[0]}">${esc(x[1].replace(/^\S+\s/,""))}</option>`).join("");await load();show("dashboard")}
async function load(){const {data,error}=await db.from("entries").select("*").eq("archived",false).order("created_at",{ascending:false});if(error)throw error;entries=data||[]}
function show(s){section=s;document.body.classList.remove("open");const item=sections.find(x=>x[0]===s);$("pageTitle").textContent=item?item[1].replace(/^\S+\s/,""):s;$("nav").querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.s===s));if(s==="dashboard")dashboard();else if(["discussion","game"].includes(s))promptCategories(s);else list(s)}
function dashboard(){const next=days(new Date(),cfg.NEXT_MEET_DATE),together=days(cfg.RELATIONSHIP_START,new Date());$("content").innerHTML=`<section class="hero"><small>WELCOME TO</small><h1>Nick &amp; Judy World</h1><p>Building our next chapter with intention, laughter and barakah.</p></section><section class="stats"><div class="stat"><small>NEXT MEETING</small><b>${next} days</b></div><div class="stat"><small>DAYS TOGETHER</small><b>${together}</b></div><div class="stat"><small>SHARED ITEMS</small><b>${entries.length}</b></div></section><h2>Our current chapter</h2><section class="grid">${cards(entries.filter(e=>e.type==="plan").slice(0,6))}</section>`}
function cards(items){if(!items.length)return '<div class="empty">Nothing here yet. Use “Add” to begin.</div>';return items.map(e=>`<article class="card"><span class="pill">${esc(e.category||e.type)}</span><h3>${esc(e.title)}</h3><p>${esc(e.details||"Ready for your notes and checklist.")}</p>${e.target_date?`<small>Target: ${esc(e.target_date)}</small>`:""}<div class="actions"><button type="button" class="light done" data-id="${e.id}" data-v="${!e.completed}">${e.completed?"Reopen":"Complete"}</button><button type="button" class="light archive" data-id="${e.id}">Archive</button></div></article>`).join("")}
function wireCards(){document.querySelectorAll(".done").forEach(b=>b.onclick=()=>toggleDone(b.dataset.id,b.dataset.v==="true"));document.querySelectorAll(".archive").forEach(b=>b.onclick=()=>archiveEntry(b.dataset.id))}
function list(type){const a=entries.filter(e=>e.type===type),cats=[...new Set(a.map(e=>e.category).filter(Boolean))];$("content").innerHTML=`<div class="filters"><button class="active" data-cat="">All</button>${cats.map(c=>`<button data-cat="${esc(c)}">${esc(c)}</button>`).join("")}</div><section class="grid" id="cards">${cards(a)}</section>`;$("content").querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("cards").innerHTML=cards(a.filter(e=>!b.dataset.cat||e.category===b.dataset.cat));wireCards()});wireCards()}
async function promptCategories(kind){const field=kind==="discussion"?"discussed":"used";try{const {data,error}=await db.from("prompts").select("*").eq("kind",kind).eq(field,false);if(error)throw error;const cats=[...new Set((data||[]).map(p=>p.category))];$("content").innerHTML=cats.length?`<div class="filters">${cats.map((c,i)=>`<button class="${i?"":"active"}" data-cat="${esc(c)}">${esc(c)}</button>`).join("")}</div><div id="promptArea" class="card empty">Choose a category.</div>`:'<div class="card empty"><h3>Everything is complete 🎉</h3></div>';$("content").querySelectorAll(".filters button").forEach(b=>b.onclick=()=>newPrompt(kind,b.dataset.cat));if(cats[0])await newPrompt(kind,cats[0])}catch(e){toast("Prompt error: "+e.message)}}
async function newPrompt(kind,cat){const field=kind==="discussion"?"discussed":"used",area=$("promptArea");const {data,error}=await db.from("prompts").select("*").eq("kind",kind).eq("category",cat).eq(field,false);if(error)return toast(error.message);if(!data.length){area.innerHTML="<h3>All prompts in this category are complete 🎉</h3>";return}const p=data[Math.floor(Math.random()*data.length)];area.className="card";area.innerHTML=`<span class="pill">${esc(cat)}</span><p class="prompt">${esc(p.question)}</p>${kind==="discussion"?'<textarea id="conclusion" placeholder="Optional agreed conclusion or note"></textarea>':'<div class="answerbox"><textarea placeholder="Nick’s answer"></textarea><textarea placeholder="Judy’s answer"></textarea></div><small>Answers are not permanently stored.</small>'}<div class="actions"><button id="finishPrompt">${kind==="discussion"?"Mark discussed":"Finish and do not repeat"}</button><button id="anotherPrompt" class="light">Another</button></div>`;$("finishPrompt").onclick=()=>finishPrompt(p.id,kind);$("anotherPrompt").onclick=()=>newPrompt(kind,cat)}
async function finishPrompt(id,kind){try{if(kind==="discussion"){const conclusion=$("conclusion")?.value.trim();if(conclusion){const {error}=await db.from("entries").insert({type:"decision",category:"Discussion conclusion",title:"Agreed conclusion",details:conclusion,created_by:user.id,status:"Agreed"});if(error)throw error}}const {error}=await db.from("prompts").update(kind==="discussion"?{discussed:true}:{used:true}).eq("id",id);if(error)throw error;toast("Saved and removed from future draws.");await promptCategories(kind)}catch(e){toast("Save failed: "+e.message)}}
function openAdd(){$("modal").showModal()}
async function saveEntry(ev){ev.preventDefault();const payload={type:$("fType").value,title:$("fTitle").value.trim(),category:$("fCategory").value.trim()||null,details:$("fDetails").value.trim()||null,status:$("fStatus").value,target_date:$("fDate").value||null,budget:$("fBudget").value||null,created_by:user.id};try{const {data,error}=await db.from("entries").insert(payload).select().single();if(error)throw error;const file=$("fPhoto").files[0];if(file){const name=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${user.id}/${Date.now()}-${name}`;const {error:up}=await db.storage.from("our-universe").upload(path,file);if(up)throw up;const {error:me}=await db.from("media").insert({entry_id:data.id,path,uploaded_by:user.id});if(me)throw me}$("modal").close();$("entryForm").reset();await load();show(section);toast("Saved permanently 💛")}catch(e){toast("Save failed: "+e.message)}}
async function toggleDone(id,v){const {error}=await db.from("entries").update({completed:v,status:v?"Completed":"In Progress",updated_at:new Date().toISOString()}).eq("id",id);if(error)return toast(error.message);await load();show(section)}
async function archiveEntry(id){if(!confirm("Archive this item?"))return;const {error}=await db.from("entries").update({archived:true}).eq("id",id);if(error)return toast(error.message);await load();show(section)}
async function start(){try{if(!cfg||!cfg.SUPABASE_URL||!cfg.SUPABASE_KEY||cfg.SUPABASE_URL.includes("PASTE_")||cfg.SUPABASE_KEY.includes("PASTE_"))throw new Error("config.js is not configured");if(!window.supabase)throw new Error("Supabase library did not load");db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_KEY);$("loginButton").onclick=login;$("signupButton").onclick=signup;$("logoutButton").onclick=logout;$("addButton").onclick=openAdd;$("menuButton").onclick=()=>document.body.classList.toggle("open");$("closeModalButton").onclick=()=>$("modal").close();$("entryForm").onsubmit=saveEntry;$("password").onkeydown=e=>{if(e.key==="Enter")login()};const {data}=await db.auth.getSession();if(data.session)await init()}catch(e){console.error(e);toast("Startup error: "+e.message)}}
document.addEventListener("DOMContentLoaded",start);